package com.makecity.client.app


object AppScreens {
	const val SPLASH_SCREEN_KEY = "SPLASH_SCREEN_KEY"
	const val FEED_SCREEN_KEY = "FEED_SCREEN_KEY"
	const val MAP_SCREEN_KEY = "MAP_SCREEN_KEY"
	const val NOTIFICATION_SCREEN_KEY = "NOTIFICATION_SCREEN_KEY"
	const val MENU_SCREEN_KEY = "MENU_SCREEN_KEY"
	const val WEB_SCREEN_KEY = "WEB_SCREEN_KEY"
	const val CITY_SCREEN_KEY = "CITY_SCREEN_KEY"
	const val ABOUT_SCREEN_KEY = "ABOUT_SCREEN_KEY"
	const val PROBLEM_SCREEN_KEY = "PROBLEM_SCREEN_KEY"
	const val AUTH_SCREEN_KEY = "AUTH_SCREEN_KEY"
	const val PROFILE_SCREEN_KEY = "PROFILE_SCREEN_KEY"
	const val EDIT_PROFILE_SCREEN_KEY = "EDIT_PROFILE_SCREEN_KEY"
	const val IMAGE_PICKER_SCREEN_KEY = "IMAGE_PICKER_SCREEN_KEY"

	const val ADDRESS_SCREEN_KEY = "ADDRESS_SCREEN_KEY"
	const val CREATE_PROBLEM_SCREEN_KEY = "CREATE_PROBLEM_SCREEN_KEY"
	const val EDIT_PROBLEM_SCREEN_KEY = "EDIT_PROBLEM_SCREEN_KEY"
	const val OWN_PROBLEMS_SCREEN_KEY = "OWN_PROBLEMS_SCREEN_KEY"
	const val SETTINGS_SCREEN_KEY = "SETTINGS_SCREEN_KEY"
	const val FILTER_PROBLEM_SCREEN_KEY = "FILTER_PROBLEM_SCREEN_KEY"
	const val MAP_ADDRESS_SCREEN_KEY = "MAP_ADDRESS_SCREEN_KEY"
	const val CAMERA_SCREEN_KEY = "CAMERA_SCREEN_KEY"
	const val CATEGORY_SCREEN_KEY = "CATEGORY_SCREEN_KEY"
	const val DESCRIPTION_SCREEN_KEY = "DESCRIPTION_SCREEN_KEY"
	const val RESTORE_SCREEN_KEY = "RESTORE_SCREEN_KEY"
	const val COMMENTS_SCREEN_KEY = "COMMENTS_SCREEN_KEY"
}